from pathlib import Path
from PIL import Image, ImageDraw, ImageFont


ROOT = Path(__file__).resolve().parents[1]
OUT_DIR = ROOT / "outputs" / "presentation-figures-20260525"
OUT_DIR.mkdir(parents=True, exist_ok=True)

real_path = ROOT / "outputs/baseline-verification-20260522/subject101_running_hand_acc16_x_periodicity.png"
raw_path = ROOT / "outputs/unified-label-conditioning-20260523/sample_stratification/running_hand_acc16_x_worst_samples.png"
constrained_path = ROOT / "outputs/latent-constraints-20260523/clip_p05_p95/sample_stratification/running_hand_acc16_x_best_samples.png"

real = Image.open(real_path).convert("RGB")
raw = Image.open(raw_path).convert("RGB")
constrained = Image.open(constrained_path).convert("RGB")

# Crop one representative waveform panel from each existing diagnostic figure.
# The source figures were generated by earlier evaluation scripts; this script
# only makes a presentation-friendly visual comparison.
crops = [
    (
        "Real running signal segment",
        "PAMAP2 subject101, hand_acc16_x",
        real.crop((250, 215, 1605, 370)),
    ),
    (
        "Raw unified synthetic example",
        "unconstrained latent",
        raw.crop((180, 125, 1885, 335)),
    ),
    (
        "Constrained synthetic example",
        "clip_p05_p95 before decoding",
        constrained.crop((180, 125, 1885, 335)),
    ),
]

W, H = 1800, 1080
canvas = Image.new("RGB", (W, H), "white")
draw = ImageDraw.Draw(canvas)

font_candidates = [
    "/System/Library/Fonts/Supplemental/Arial.ttf",
    "/System/Library/Fonts/Supplemental/Arial Bold.ttf",
    "/System/Library/Fonts/Helvetica.ttc",
]
try:
    title_font = ImageFont.truetype(font_candidates[1], 46)
    subtitle_font = ImageFont.truetype(font_candidates[0], 27)
    label_font = ImageFont.truetype(font_candidates[1], 30)
    small_font = ImageFont.truetype(font_candidates[0], 22)
except Exception:
    title_font = subtitle_font = label_font = small_font = ImageFont.load_default()

draw.text((70, 42), "Running waveform comparison: real vs generated", fill=(15, 23, 42), font=title_font)
draw.text(
    (70, 100),
    "These panels are for qualitative inspection; they are not TSGBench metrics.",
    fill=(71, 85, 105),
    font=subtitle_font,
)

panel_x = 70
panel_w = W - 140
panel_h = 245
gap = 55
y0 = 170

for i, (label, desc, img) in enumerate(crops):
    y = y0 + i * (panel_h + gap)
    draw.rounded_rectangle((panel_x, y, panel_x + panel_w, y + panel_h), radius=14, outline=(216, 222, 233), width=2, fill=(255, 255, 255))
    draw.text((panel_x + 22, y + 16), label, fill=(15, 23, 42), font=label_font)
    draw.text((panel_x + 22, y + 54), desc, fill=(100, 116, 139), font=small_font)

    plot_x = panel_x + 430
    plot_y = y + 22
    plot_w = panel_w - 465
    plot_h = panel_h - 44
    img.thumbnail((plot_w, plot_h), Image.Resampling.LANCZOS)
    px = plot_x + (plot_w - img.width) // 2
    py = plot_y + (plot_h - img.height) // 2
    canvas.paste(img, (px, py))

draw.rounded_rectangle((70, 1010, W - 70, 1050), radius=10, fill=(236, 253, 245), outline=(236, 253, 245))
draw.rectangle((70, 1010, 82, 1050), fill=(15, 118, 110))
draw.text(
    (100, 1018),
    "Main visual point: raw unified generation can produce unrealistic amplitudes; latent constraint restores a plausible waveform scale.",
    fill=(19, 78, 74),
    font=small_font,
)

out = OUT_DIR / "running_real_raw_unified_constrained_waveform_comparison.png"
canvas.save(out, quality=95)
print(out)
