name: time_series

blocks:
  - name: trainer
    type: public/trainers/sdforger-tuning
    model_id_or_path: gpt2
    learning_rate: 0.00008
    num_train_epochs: 3
    per_device_train_batch_size: 8
    seed: 42

target:
  type: vllm
  dtype: float32
  trust_remote_code: true
  ignore_mismatched_sizes: true
  temperature: 1.1
  max_tokens: 400

metadata:
  version: 1.0
